FROM openjdk:11

COPY /home/rudi/developpement/target/demo-docker-0.0.1-SNAPSHOT.jar /usr/app/

WORKDIR /usr/app

# Make port 8000 available to the world outside this container
EXPOSE 8000

RUN sh -c 'touch demo-docker-0.0.1-SNAPSHOT.jar'

ENTRYPOINT ["java","-jar","demo-docker-0.0.1-SNAPSHOT.jar"]